#

bankofquestions = [
    {"question": "Which Disney character famously leaves a glass slipper behind at a royal ball?",
     "choices": ["Pocahontas",
                 "Cinderella",
                 "Sleeping Beauty",
                 "Elsa"], "answer": "Cinderella", "audio": "Q0.mp3"},
    {"question": "The hammer and sickle is one of the most recognisable symbols of which political ideology?",
     "choices": ["Republicanism",
                 "Communism",
                 "Conservatism",
                 "Liberalism"], "answer": "Communism", "audio": "Q1.mp3"},
    {"question": " What does the word loquacious mean?", "choices": ["Angry",
                                                                     "Chatty",
                                                                     "Beautiful",
                                                                     "Shy"], "answer": "Chatty", "audio": "Q2.mp3"},
    {"question": "Obstetrics is a branch of medicine particularly concerned with what?", "choices": ["Childbirth",
                                                                                                     "Broken bones",
                                                                                                     "Heart conditions",
                                                                                                     "Old age"],
     "answer": "Childbirth", "audio": "Q3.mp3"},
    {"question": "Which of these religious observances lasts for the shortest period of time during the calendar year?",
     "choices": ["Ramadan",
                 "Diwali",
                 "Lent",
                 "Hanukkah"], "answer": "Diwali", "audio": "Q4.mp3"},
    {"question": "Construction of which of these famous landmarks was completed first?",
     "choices": ["Empire State Building",
                 "Royal Albert Hall",
                 "Eiffel Tower",
                 "Big Ben Clock Tower"], "answer": "Big Ben Clock Tower", "audio": "Q5.mp3"},
    {"question": 'Which of these cetaceans is classified as a "toothed whale?"', "choices": ["Gray whale",
                                                                                             "Minke Whale",
                                                                                             "Sperm Whale",
                                                                                             "Humpback whale"],
     "answer": "Sperm Whale", "audio": "Q6.mp3"},
    {"question": "In 1718, which pirate died in battle off the coast of what is now North Carolina?",
     "choices": ["Calico Jack",
                 "Blackbeard",
                 "Bartholomew Roberts",
                 "Captain Kidd"], "answer": "Blackbeard", "audio": "Q7.mp3"},
    {"question": "What sort of animal is Walt Disney's Dumbo?", "choices": ["Deer",
                                                                            "Rabbit",
                                                                            "Donkey",
                                                                            "Elephant"], "answer": "Elephant",
     "audio": "Q8.mp3"},
    {"question": "What is the Celsius equivalent of 77 degrees Fahrenheit?", "choices": ["15",
                                                                                         "20",
                                                                                         "25",
                                                                                         "35"], "answer": "25",
     "audio": "Q9.mp3"},
    {"question": 'Which Shakespeare play features the line "Neither a borrower nor a lender be"?', "choices": ["Hamlet",
                                                                                                               "Macbeth",
                                                                                                               "Othello",
                                                                                                               "The Merchant of Venice"],
     "answer": "Hamlet", "audio": "Q10.mp3"},
    {"question": "Which is the largest city in the USA's largest state by area?", "choices": ["Dallas",
                                                                                              "Los Angeles",
                                                                                              "New York",
                                                                                              "Sitka"],
     "answer": "Sitka", "audio": "Q11.mp3"},
    {"question": 'Which insect shorted out an early supercomputer and inspired the term "computer bug"?',
     "choices": ["Moth",
                 "Roach",
                 "Fly",
                 "Japanese beetle"], "answer": "Moth", "audio": "Q12.mp3"},
    {"question": "Which of the following men does not have a chemical element named for him?",
     "choices": ["Albert Einstein",
                 "Niels Bohr",
                 "Isaac Newton",
                 "Enrico Fermi"], "answer": "Isaac Newton", "audio": "Q13.mp3"},
    {
        "question": "According to the Population Reference Bureau, what is the approximate number of people who have ever lived on earth?",
        "choices": ["50 billion",
                    "100 billion",
                    "1 trillion",
                    "5 trillion"], "answer": "100 billion", "audio": "Q14.mp3"},
    {"question": "What word can be put in front of the words 'track', 'way' and 'horse' to make three other words?",
     "choices": ["Road",
                 "Sound",
                 "Cross",
                 "Race"], "answer": "Race", "audio": "Q15.mp3"},
    {"question": "Which of these cartoon characters is a rodent?", "choices": ["Speedy Gonzalez",
                                                                               "Wile E. Coyote",
                                                                               "Tasmanian Devil",
                                                                               "Road Runner"],
     "answer": "Speedy Gonzalez", "audio": "Q16.mp3"},
    {"question": "In the Old Testament, who, with God's help, parted the Red Sea?", "choices": ["Moses",
                                                                                                "Noah",
                                                                                                "Jonah",
                                                                                                "Joseph"],
     "answer": "Moses", "audio": "Q17.mp3"},
    {"question": "Which month of the year was named after Julius Caesar?", "choices": ["October",
                                                                                       "June",
                                                                                       "July",
                                                                                       "August"], "answer": "July",
     "audio": "Q18.mp3"},
    {"question": "Which Amendment granted women the right to vote in the USA?", "choices": ["17th",
                                                                                            "19th",
                                                                                            "25th",
                                                                                            "21st"], "answer": "19th",
     "audio": "Q19.mp3"},
    {"question": "What video game characters specialize in plumbing?", "choices": ["Mario and Luigi",
                                                                                   "Sonic and Tails",
                                                                                   "Mega Man and Samus",
                                                                                   "Sans and Papyrus"],
     "answer": "Mario and Luigi", "audio": "Q20.mp3"},
    {"question": "Raleigh is the capital of which State?", "choices": ["South Dakota",
                                                                       "North Carolina",
                                                                       "Mississippi",
                                                                       "Tennessee"], "answer": "North Carolina",
     "audio": "Q21.mp3"},
    {"question": "What pet is the most popular pet in the USA?", "choices": ["Dogs",
                                                                             "Cats",
                                                                             "Fish",
                                                                             "Hamsters"], "answer": "Fish",
     "audio": "Q22.mp3"},
    {"question": "Which flies a green, white, and orange (in that order) tricolor flag", "choices": ["Ireland",
                                                                                                     "Ivory Coast",
                                                                                                     "Italy",
                                                                                                     "India"],
     "answer": "Ireland", "audio": "Q23.mp3"},
    {"question": "Which of the following is NOT a fruit", "choices": ["Banana",
                                                                      "Rhubarb",
                                                                      "Tomatoes",
                                                                      "Avocados"], "answer": "Rhubarb",
     "audio": "Q24.mp3"},
    {"question": "If you were looking at Iguazu Falls, on what continent would you be?", "choices": ["Asia",
                                                                                                     "Africa",
                                                                                                     "South America",
                                                                                                     "North America"],
     "answer": "South America", "audio": "Q25.mp3"},
    {"question": "Which of the following languages has the longest alphabet?", "choices": ["Greek",
                                                                                           "Tamil",
                                                                                           "Russian",
                                                                                           "Arabic"],
     "answer": "Russian", "audio": "Q26.mp3"},
    {"question": "The fear of insects is known as what?", "choices": ["Arithmophobia",
                                                                      "Entomophobia",
                                                                      "Arachnophobia",
                                                                      "Ailurophobia"], "answer": "Entomophobia",
     "audio": "Q27.mp3"},
    {"question": "Which horoscope sign is a fish?", "choices": ["Aquarius",
                                                                "Cancer",
                                                                "Libra",
                                                                "Pisces"], "answer": "Pisces", "audio": "Q28.mp3"},
    {"question": "Which Game of Thrones character is known as the Young Wolf?", "choices": ["Eddard Stark",
                                                                                            "Robb Stark",
                                                                                            "Arya Stark",
                                                                                            "Sansa Stark"],
     "answer": "Robb Stark", "audio": "Q29.mp3"},
    {"question": "What is the strongest muscle in the human body?", "choices": ["Jaw",
                                                                                "Tongue",
                                                                                "Heart",
                                                                                "Glutes"], "answer": "Jaw",
     "audio": "Q30.mp3"},
    {"question": "What is the average weight of the human brain?", "choices": ["14 kilos",
                                                                               "14 grams",
                                                                               "4 kilos",
                                                                               "41 grams"], "answer": "4 kilos",
     "audio": "Q31.mp3"},
    {"question": "What is the rarest blood type?", "choices": ["O+",
                                                               "A-",
                                                               "B+",
                                                               "AB-"], "answer": "AB-", "audio": "Q32.mp3"},
    {"question": "What is the name of the first human civilization?", "choices": ["Babylonia",
                                                                                  "The Indus Valley",
                                                                                  "Egypt",
                                                                                  "Mesopotamia"],
     "answer": "Mesopotamia", "audio": "Q33.mp3"},
    {"question": "In which country was the largest known T-Rex skeleton found?", "choices": ["China",
                                                                                             "New Zealand",
                                                                                             "Canada",
                                                                                             "India"],
     "answer": "Canada", "audio": "Q34.mp3"},
    {"question": "A dog sweats through which part of its body?", "choices": ["Ears",
                                                                             "Paws",
                                                                             "Fur",
                                                                             "Tail"], "answer": "Paws",
     "audio": "Q35.mp3"},
    {"question": "Which insect can fly forward, backward and sideways?", "choices": ["Dragonfly",
                                                                                     "Grasshopper",
                                                                                     "Honey Bee",
                                                                                     "Ladybug"], "answer": "Dragonfly",
     "audio": "Q36.mp3"},
    {"question": "How long is a marathon in miles?", "choices": ["26.2",
                                                                 "26.3",
                                                                 "26.4",
                                                                 "26.5"], "answer": "26.2", "audio": "Q37.mp3"},
    {"question": "Who is the richest investor in the world?", "choices": ["Elon Musk",
                                                                          "Bill Gates",
                                                                          "Steve Jobs",
                                                                          "Warren Buffet"], "answer": "Warren Buffet",
     "audio": "Q38.mp3"},
    {"question": "What is the slogan of Apple Inc.?", "choices": ["Be What's Next",
                                                                  "Think Different",
                                                                  "Do What You Can't",
                                                                  "Make. Believe"], "answer": "Think Different",
     "audio": "Q39.mp3"},
    {"question": "What item is in every Fight Club scene?", "choices": ["Coca Cola Can",
                                                                        "Starbucks Cup",
                                                                        "Dunkin Donut",
                                                                        "Pepsi Bottle"], "answer": "Starbucks Cup",
     "audio": "Q40.mp3"},
    {"question": "What is the name for a traditional Argentine music and dance?", "choices": ["Bharatnatyam",
                                                                                              "Highland Dance",
                                                                                              "Tango",
                                                                                              "Kecak Dance"],
     "answer": "Tango", "audio": "Q41.mp3"},
    {"question": "What is the oldest city in the world?", "choices": ["Damascus",
                                                                      "Athens",
                                                                      "Jerusalem",
                                                                      "Tel Aviv"], "answer": "Damascus",
     "audio": "Q42.mp3"},
    {"question": "What is the driest place on Earth?", "choices": ["Sahara Desert",
                                                                   "Atacama Desert",
                                                                   "McMurdo, Antarctica",
                                                                   "Kufra, Libya"], "answer": "McMurdo, Antarctica",
     "audio": "Q43.mp3"},
    {"question": "What was the original name of Mickey Mouse?", "choices": ["Mortimer Mouse",
                                                                            "The Rat",
                                                                            "Marvin Mouse",
                                                                            "Marshall Mouse"],
     "answer": "Mortimer Mouse", "audio": "Q44.mp3"},
    {"question": "Who sings Poker Face?", "choices": ["Madonna",
                                                      "Lady Gaga",
                                                      "Miley Cyrus",
                                                      "Brittany Spears"], "answer": "Lady Gaga", "audio": "Q45.mp3"},
    {"question": 'What did Aladdin steal in the marketplace at the beginning of "Aladdin"', "choices": ["Apple",
                                                                                                        "Bread",
                                                                                                        "Gold",
                                                                                                        "Rice"],
     "answer": "Bread", "audio": "Q46.mp3"},
    {"question": 'Which College Is Elle Applying For In Legally Blonde?', "choices": ["Yale",
                                                                                      "Princeton",
                                                                                      "Harvard",
                                                                                      "Duke"], "answer": "Harvard",
     "audio": "Q47.mp3"},
    {"question": 'Which one of the following is the largest ocean in the world?', "choices": ["Indian Ocean",
                                                                                              "Atlantic Ocean",
                                                                                              "Arctic Ocean",
                                                                                              "Pacific Ocean"],
     "answer": "Pacific Ocean", "audio": "Q48.mp3"},
    {"question": 'Sodium Hydrogen Bicarbonate is a scientific name of which common thing?', "choices": ["Heavy Cream",
                                                                                                        "Baking Soda",
                                                                                                        "Carbonated Water",
                                                                                                        "Table Salt"],
     "answer": "Baking Soda", "audio": "Q49.mp3"},
    {"question": 'What type of scientist studies living plants?', "choices": ["Paleantologist",
                                                                              "Botanist",
                                                                              "Geoligist",
                                                                              "Entomologist"], "answer": "Botanist",
     "audio": "Q50.mp3"},
    {"question": 'A lobster’s teeth are located in which part of its body?', "choices": ["Stomach",
                                                                                         "Mouth",
                                                                                         "Claw",
                                                                                         "Legs"], "answer": "Stomach",
     "audio": "Q51.mp3"},
    {"question": 'Hickory trees produce which types of nuts?', "choices": ["Pistachios",
                                                                           "Walnuts",
                                                                           "Macadamia",
                                                                           "Pecan"], "answer": "Pecan",
     "audio": "Q52.mp3"},
    {"question": 'What are made and repaired by a cobbler?', "choices": ["Shoes",
                                                                         "Roads",
                                                                         "Windows",
                                                                         "Jewellery"], "answer": "Shoes",
     "audio": "Q53.mp3"},
    {"question": 'In what year was the first iPhone released?', "choices": ["2000",
                                                                            "2004",
                                                                            "2007",
                                                                            "2009"], "answer": "2007",
     "audio": "Q54.mp3"},
    {"question": 'What colour were the Pyramids of Giza originally?', "choices": ["Orange",
                                                                                  "Blue",
                                                                                  "Pink",
                                                                                  "White"], "answer": "White",
     "audio": "Q55.mp3"},
    {"question": 'Lebanon is a country on which continent?', "choices": ["Africa",
                                                                         "Asia",
                                                                         "South America",
                                                                         "Europe"], "answer": "Asia",
     "audio": "Q56.mp3"},
    {"question": 'How many blue stripes are there on the U.S. flag?', "choices": ["6",
                                                                                  "7",
                                                                                  "13",
                                                                                  "0]"], "answer": "13",
     "audio": "Q57.mp3"},
    {"question": 'How many blue stripes are there on the U.S. flag?', "choices": ["Dragon",
                                                                                  "Rabbit",
                                                                                  "Dog",
                                                                                  "Lion"], "answer": "Lion",
     "audio": "Q58.mp3"},
    {"question": 'What was the first feature-length animated film ever released?', "choices": ["Pinocchio",
                                                                                               "Fantasia",
                                                                                               "Snow White and the Seven Dwarfs",
                                                                                               "Dumbo"],
     "answer": "Snow White and the Seven Dwarfs", "audio": "Q59.mp3"},
    {"question": 'What was the last movie Walt Disney was able to work on before he died?', "choices": ["Mary Poppins",
                                                                                                        "101 Dalmatians",
                                                                                                        "The Jungle Book",
                                                                                                        "The Sword in the Stone"],
     "answer": "The Jungle Book", "audio": "Q60.mp3"},
    {"question": 'What NBA player has won the most league MVPs?', "choices": ["LeBron James",
                                                                              "Michael Jordan",
                                                                              "Kareem Abdul-Jabbar",
                                                                              "Stephen Curry"],
     "answer": "Kareem Abdul-Jabbar", "audio": "Q61.mp3"},
    {"question": 'What’s the top number of a fraction called?', "choices": ["Denominator",
                                                                            "Numerator",
                                                                            "Decimal",
                                                                            "Fractional"], "answer": "Numerator",
     "audio": "Q62.mp3"},
    {"question": 'What is the warmest sea on Earth?', "choices": ["Dead sea",
                                                                  "White sea",
                                                                  "Red sea",
                                                                  "Black sea"], "answer": "Red sea",
     "audio": "Q63.mp3"},
    {"question": 'What is the only major city located on two continents?', "choices": ["Reykjavik",
                                                                                       "Istanbul",
                                                                                       "Mowcow",
                                                                                       "Madrid"], "answer": "Istanbul",
     "audio": "Q64.mp3"},
    {"question": 'What year did India gain its independence from Britain?', "choices": ["1938",
                                                                                        "1942",
                                                                                        "1947",
                                                                                        "1949"], "answer": "1947",
     "audio": "Q65.mp3"},
    {"question": 'In what month is Earth closest to the sun?', "choices": ["May",
                                                                           "June",
                                                                           "January",
                                                                           "April"], "answer": "January",
     "audio": "Q66.mp3"},
    {"question": 'What is the only edible food that never expires?', "choices": ["White rice",
                                                                                 "Honey",
                                                                                 "Rye",
                                                                                 "Barley"], "answer": "Honey",
     "audio": "Q67.mp3"},
    {"question": 'What condiment was sold in the 1830’s as medicine?', "choices": ["Soy sauce",
                                                                                   "Ranch dressing",
                                                                                   "Ketchup",
                                                                                   "Maple syrup"], "answer": "Ketchup",
     "audio": "Q68.mp3"},
    {"question": 'What is the technical term for the “brain” of your computer?', "choices": ["Hard drive",
                                                                                             "RAM",
                                                                                             "CPU",
                                                                                             "Motherboard"],
     "answer": "CPU", "audio": "Q69.mp3"},
    {"question": 'What was Google’s original name?', "choices": ["Googol",
                                                                 "Oneshot",
                                                                 "Typist",
                                                                 "Backrub"], "answer": "Backrub", "audio": "Q70.mp3"},
    {"question": 'What year was the first color photograph taken?', "choices": ["1861",
                                                                                "1885",
                                                                                "1894",
                                                                                "1899"], "answer": "1861",
     "audio": "Q71.mp3"},
    {"question": 'What animal hibernates the longest?', "choices": ["Bears",
                                                                    "Snail",
                                                                    "Koala",
                                                                    "Sloth"], "answer": "Snail", "audio": "Q72.mp3"},
    {"question": 'What animal is known to have the most powerful bite in the world?', "choices": ["Nile Crocodile",
                                                                                                  "Hippopotamus",
                                                                                                  "Hyena",
                                                                                                  "Grizzly Bear"],
     "answer": "Nile Crocodile", "audio": "Q73.mp3"},
    {"question": 'What country has a unicorn as its national animal?', "choices": ["New Zealand",
                                                                                   "Ireland",
                                                                                   "Scotland",
                                                                                   "Sweden"], "answer": "Scotland",
     "audio": "Q74.mp3"},
    {"question": 'How many floors does the Eiffel Tower have?', "choices": ["6",
                                                                            "5",
                                                                            "4",
                                                                            "3"], "answer": "3", "audio": "Q75.mp3"},
    {"question": 'Which flag is not rectangular?', "choices": ["Vatican City",
                                                               "Lithuania",
                                                               "Nepal",
                                                               "Laos"], "answer": "Nepal", "audio": "Q76.mp3"},
    {"question": 'What is the currency of Somaliland', "choices": ["Shillings",
                                                                   "Pounds",
                                                                   "Rand",
                                                                   "Dirham"], "answer": "Shillings",
     "audio": "Q77.mp3"},
    {"question": 'What does "WWE" stand for?', "choices": ["Wrestlers Worldwide Evolution",
                                                           "World Wrestling Equinox",
                                                           "World Wrestling Entertainment",
                                                           "Willy Wonka Eatery"],
     "answer": "World Wrestling Entertainment", "audio": "Q78.mp3"},
    {"question": 'Who is the most followed person on Instagram?', "choices": ["Kylie Jenner",
                                                                              "Taylor Swift",
                                                                              "Cristiano Ronaldo",
                                                                              "Selena Gomez"],
     "answer": "Cristiano Ronaldo", "audio": "Q79.mp3"},
    {"question": 'Before independence, what was Bangladesh called?', "choices": ["Ceylon",
                                                                                 "Formosa",
                                                                                 "Little India",
                                                                                 "East Pakistan"],
     "answer": "East Pakistan", "audio": "Q80.mp3"},
    {"question": 'What is the tallest building in the world?', "choices": ["The Burg Khalifa, UAE",
                                                                           "Shanghai Tower, China",
                                                                           "CN Tower, Canada",
                                                                           "Merdeka 118, Malaysia"],
     "answer": "The Burg Khalifa, UAE", "audio": "Q81.mp3"},
    {"question": 'Who directed the movie "Kill Bill?""', "choices": ["Steven Spielberg",
                                                                     "Quentin Tarantino",
                                                                     "Christopher Nolan",
                                                                     "Guillermo Del Toto"],
     "answer": "Quentin Tarantino", "audio": "Q82.mp3"}]




